### ISSUE TITLE
 November 15th, 2018 Planned Network Upgrade and propaganda

### ISSUE THREAD

**Issue by maesitos** [bitcoincashorg/bitcoincash.org#105]
Isn't using the website to just show only one side of the proposed changes an attempt to invalidate the governance based on hashing power?

![screen shot 2018-08-24 at 13 14 26](https://user-images.githubusercontent.com/3597038/44581846-a5512f80-a79f-11e8-96f8-01299da32caa.png)

> Businesses and individuals who use the Bitcoin Cash network should check to ensure that their software is compatible with the upgrade.

This assumes you know already the outcome of the upgrade  👆

This is trying to control Bitcoin Cash by developers and not by hashing power as per the white paper section 12, and we know how that ends.

I'm referring my customers to this website as it's the de facto official website but I'll switch gears if you start to use it to promote your particular views and not show the whole picture.

**Comment by gabrieldov** [comment]
<crickets>

**Comment by gabrieldov** [comment]
<img src="https://www.statefansnation.com/wp-content/uploads/2010/11/crickets.gif">

**Comment by BUYMERCIER** [comment]
@maesitos Thank you for you for your remark.
For now, there is no "other side for the change" as [https://github.com/bitcoin-sv](https://github.com/bitcoin-sv) is an empty repository. There is no other implementation.

If there is a significant debate, we will do our best to have viewers make up their own mind.

**Comment by BUYMERCIER** [comment]
@maesitos Thank you for you for your remark.
For now, there is no "other side for the change" as https://github.com/bitcoin-sv is an empty repository. There is no other implementation.

If there is a significant debate, we will do our best to have viewers make up their own mind.

**Comment by maesitos** [comment]
Even if there isn’t any alternative implementation. You put it as if the proposed changes were going to go through when in reality you don’t know if you have the hash power to back it.

Neutral is to indicate the hashing power will determine the outcome.

**Comment by BUYMERCIER** [comment]
> You put it as if the proposed changes were going to go through when in reality you don’t know if you have the hash power to back it.

For now, only one miner announced they would support a different implementation from what is currently listed on the website, with approximately 25% of the hashrate.
Please wait until miners gather and decide as well as nChain's software introduction next Thursday.

Again:
> If there is a significant debate, we will do our best to have viewers make up their own mind.

**Comment by maesitos** [comment]
Any network upgrade should show clearly to the user it's a proposal that needs miner's confirmation. Bitcoin's governance is important, or, Bitcoin's model is broken. In fact the word '_network upgrade_' is completely wrong and misleading in this context as changing the code of one of the implementations isn't a network upgrade.

**Comment by BUYMERCIER** [comment]
Please, submit a pull request with the appropriate changes.
