### ISSUE TITLE
CashAddress hash methods for P2KH and P2SH not specified 

### ISSUE THREAD

**Issue by crawfobw** [bitcoincashorg/bitcoincash.org#121]
https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md#hash

Hash methods for P2KH and P2SH aren't specified here. I assume the method is just PubKey -> SHA-256 -> RIPEMD160 however it would be nice to get some clarification from the spec.

**Comment by merc1er** [comment]
@crawfobw was this resolved?
