### ISSUE TITLE
Wrong date on malfix document

### ISSUE THREAD

**Issue by markblundeberg** [bitcoincashorg/bitcoincash.org#124]
https://github.com/bitcoincashorg/bitcoincash.org/blob/master/workgroups/wg-malfix/summaries/20180130%20-%20Meeting%20Summary.md

Says "20170129"

**Comment by maplesyrupsucker** [comment]
@BUYMERCIER @Mengerian Can you guys have a peek at this and put in a PR?

**Comment by BUYMERCIER** [comment]
See PR #128. Thank you @markblundeberg
