### ISSUE TITLE
Remove Unit Wallet from list of wallets

### ISSUE THREAD

**Issue by imaginaryusername** [bitcoincashorg/bitcoincash.org#147]
Unit Wallet is now defunct, with its website, Github, Twitter and Yours account all deleted, and confirmed by Maemon. Please remove from the list of wallets.

**Comment by BUYMERCIER** [comment]
Thank you for bringing that up! And sorry for the late reply. I will do a little cleaning of unmaintained projects.

**Comment by BUYMERCIER** [comment]
https://github.com/bitcoincashorg/bitcoincash.org/tree/header-redesign
