### ISSUE TITLE
Could OP_CHECKDATASIG be used to implement an anti-money laundering system?

### ISSUE THREAD

**Issue by monkeylord** [bitcoincashorg/bitcoincash.org#158]
As far as I know, governments always seek supervisions.
If data outside blockchain could be used to judge whether a transaction be accept or not, could governments build a signing authority?  So they can enforce all the exchanges only accept deposit with SA sign.
In my limited thought, a SA would be enough to build walls and gates, which can split bitcoin into legal and illegal.

Am I wrong? 
I am worrying about it.

**Comment by imaginaryusername** [comment]
The coercion method you described has always been possible with simple multisig.

**Comment by monkeylord** [comment]
> The coercion method you described has always been possible with simple multisig.

Well, that's quite a ... comfort.

However, will OP_CHECKDATASIG make it much easier?
With OP_CHECKDATASIG, a CA is capable enough to do the job, which means no need to build new infrastructure.

**Comment by imaginaryusername** [comment]
No, if you use CDS to make things "easier" in that the signing party is agnostic of what transaction is being approved and simply signing a neutral string, then it cannot be used for censorship as any transaction can make use of it. It'll either work that way (useless for censorship) or be used to sign things specific to the transaction (hence equivalent to checksig).

**Comment by monkeylord** [comment]
> No, if you use CDS to make things "easier" in that the signing party is agnostic of what transaction is being approved and simply signing a neutral string, then it cannot be used for censorship as any transaction can make use of it. It'll either work that way (useless for censorship) or be used to sign things specific to the transaction (hence equivalent to checksig).

Well, but if we look at it like this?
A federal system is not capable of investigating all the transactions, so it's literally can't do the approving.
But with CDS, state governments or even county governments can be authorized to do investigations.
Moreover, the signing chain can be traced down, so corrupt officers can be found.
International cooperation is also enabled.

**Comment by imaginaryusername** [comment]
It still does not refute the fact that the exact same thing can already be done with checksig. CDS does not enable anything new in censorship under all circumstances.

**Comment by dgenr8** [comment]
There's also nothing special about the CDS opcode in this regard. To the extent that similar function is available using custom scripts, it can be used the same way. If some private entity tries to patent those scripts, you're just swapping out the government for a private entity.

**Comment by monkeylord** [comment]
> There's also nothing special about the CDS opcode in this regard. To the extent that similar function is available using custom scripts, it can be used the same way. If some private entity tries to patent those scripts, you have the additional problem of needing a patent license.

There's another questions.
It seems that CDS could be used to extend transaction.
One could append some custom fields in scripts, which would be verified onchain.

So, governments could enforce some onchain stamping with CDS, like who(real identity) is doing the transaction.
These information could be recorded in transaction, but cannot not be verified onchain without CDS.

Am I correct?

**Comment by monkeylord** [comment]
> > Am I correct?
> 
> No, my whole point was that it can be done without CDS also.

But with CDS, it can be done onchain. Isn't it?

Here's the model, a "legal" TX:
|Standard TX|Legal Information|
Legal Information is what governments want included in TX.

"legal" TX with CDS:
Signing is about both TX and Legal Information, illegal "legal" TX is rejected automatically.

"legal" TX without CDS:
Signing is about TX only, legal Information can be faked, and must be verified offchain.

**Comment by BUYMERCIER** [comment]
> But with CDS, it can be done onchain. Isn't it?
Just like with multisig.

> I am worrying about it.
Do not keep your Bitcoins on an exchange platform, as long as you control the private keys you do not have to worry about this.
