### ISSUE TITLE
BCH testnet details unclear

### ISSUE THREAD

**Issue by jcramer** [bitcoincashorg/bitcoincash.org#17]
Hi,  I have lots of questions here, so please bear with me. :-)

The instructions and details for joining BCH testnets are not clear to me.  Its also not clear which testnets are being used for what.  Are testnets development team specific, or is there an effort to have the same testnets across different teams?

The following link is provided on the front page of bitcoin cash.org for testnets, and does provide some description of two different testnets but it isn't clear.  I was surprised that testnet3 isn't listed at all here, which is the default testnet when setting testnet=1 in bitcoin.conf.
[https://docs.google.com/spreadsheets/d/1_uJryqNnMEHogUdCY6WhCMoyuyoZsyMtVm2R4xAsIeI/edit#gid=299033565](https://docs.google.com/spreadsheets/d/1_uJryqNnMEHogUdCY6WhCMoyuyoZsyMtVm2R4xAsIeI/edit#gid=299033565)

I just want to understand the testnets, how to get on the different testnets, and which testnets have which features.  For example, if I want to be able test new features before the mainnet forks, is there a fixed testnet for this?  Or if I just want to use a testnet that has the same features as the main net, is there a fixed testnet for this?  What are the explicit instructions for joining these nets?  

In the google spreadsheet above there are some brief instructions but there's no mention about setting `testnet=1` in the bitcoin.conf file... I would think this is needed, but again just not clear to me.

On a side note, within that google spreadsheet there is also a link for a slack chat at btcforks.signup.team, but that link doesn't work.  Is there a slack for testnet discussion?

**Comment by schancel** [comment]
`testnet3` is a legacy name that is used for the datadir when on the testnet.  The other names were given by bitPrim engineers who were running a public testnet.  They were running two testnets on the fork:

testnet1 -- post-activation.  Allows you to try new opcodes.
testnet2 -- repeatedly reset with progressive activation times for the upgrade to ensure that upgrading the protocol does not have issues.

Neither of these testnets are necessary now and may be offline.  The regular testnet can be used now for.

**Comment by jcramer** [comment]
ok got it.  thank you for the clarifications.
