### ISSUE TITLE
cashaddr spec doesn't contain test vectors for >160 bit lengths.

### ISSUE THREAD

**Issue by Steve132** [bitcoincashorg/bitcoincash.org#18]
CashAddr supports >160 bit lengths by design, and parsers are expected to detect and verify that the version byte contains the same size as the payload according to a set mapping between the version bits and the sizes they represent.

It is difficult to test this in an implementation without test vectors.  In fact, without test vectors in the spec, many people *miss* that it's a requirement or don't correctly report it.  I've already found two implementations in the wild who didn't realize this and don't initially conform to this part of the spec.  (disclosure, mine was one of them).

Adding test vectors for >160 bit modes of CashAddr to the spec would help maintainers to realize this is required when their implementations fail to pass, which will help prevent errors in the future imho.

**Comment by schancel** [comment]
A pull request would be wonderful.

**Comment by Steve132** [comment]
I made a pull request https://github.com/bitcoincashorg/bitcoincash.org/pull/24

Perhasps they would be better in a separate file, but here they are.
