### ISSUE TITLE
Move Bitcoincash protocol upgrade specifications directory away from web repository

### ISSUE THREAD

**Issue by sickpig** [bitcoincashorg/bitcoincash.org#183]
It used to be like that and I think that we should move back to that way of laying out things. 

Having the specifications stored in bitcoincash.org website code repo make harder for people to find them out, more to the point it's not the right place where to store protocol documentation.

Another side effects of this way of organize things is that people who have write access to the web repository could merge specifications into the tree. This is not as bad as it seems because a PR to be merged need to be approved by a minimum number of devs, but still not ideal.

To make a long story short, moving specifications doc on a separate ad-hoc repo:

- is clearer,
- makes easier to find specs,
- and lastly keep web code separated from protocol documentation.

**Comment by dgenr8** [comment]
> This is not as bad as it seems because a PR to be merged need to be approved by a minimum number of devs, but still not ideal.

The spec that split the chain was approved only by somebody named @Platinumwrist and merged by @maplesyrupsucker.  Nobody cared and I was accused of "pot-stirring" for bringing it up.

https://github.com/bitcoincashorg/bitcoincash.org/pull/94

**Comment by sickpig** [comment]
@Mengerian @schancel what do you think?

**Comment by schancel** [comment]
@sickpig I personally think having it in this repository is preferable, as the web team can easily render it with jekyll and get it hosted.  There probably should just be a link to the github repo from whatever page that index is on.  

Getting this easily accessible from bitcoincash.org I think is the most critical thing.

However, this is just one man's opinion (Although I'm the person that put it in here in the first place).  It wouldn't offend me if it were moved due to group conscience.

**Comment by maplesyrupsucker** [comment]
There's a branch that's being worked on that includes links to developer docs, workgroups, and more which should make these specs much easier to find in the future.

**Comment by sickpig** [comment]
@maplesyrupsucker thanks for doing that. I think it should improve the current situation.

That said one thing that I forgot to mention in the initial post is related to the way issues and PRs for the website and protocol specifications are mixed up.

I find it weird but it could be just me. 

@schancel 

> I personally think having it in this repository is preferable, as the web team can easily render it with jekyll and get it hosted

You have a point, still getting the specification easily accessible from bitcoincash.org could be achieved via git subtree/submodule. This will maintain the convenience of having the specs easily accessible from bitcoincash.org and additionally bring more clarity to the revision process (by the means of keeping spec and web PRs/Issues in two separate queues).

Having said that mine was just a nit pick if you will. I can leave with that.

**Comment by schancel** [comment]
@sickpig I agree.  I also found it weird.  Maybe the key is to get more people working on this and get those pull requests cleared out faster?

**Comment by Mengerian** [comment]
Personally, I don't mind the monorepo setup, but I think it would be nice to separate the web stuff into its own top-level folder. Right now, when you look at the repo, it's filled with website-specific stuff like layouts and fonts. That distracts from the Spec folder and other dev-specific information like workgroups.

@maplesyrupsucker How difficult would it be to separate all the website stuff inside a "website" directory? And then Spec and workgroups, for example, could be other top-level directories alongside that?

Having a "developers" section on the website should also help significantly, I know you guys are working on that.

**Comment by maplesyrupsucker** [comment]
@sickpig 
> That said one thing that I forgot to mention in the initial post is related to the way issues and PRs for the website and protocol specifications are mixed up.
> 
> I find it weird but it could be just me.


Good points – we could begin labeling issues / PR's with website vs specifications to keep things a bit more color coded and easier to digest and filter. 

@Mengerian 
>@maplesyrupsucker How difficult would it be to separate all the website stuff inside a "website" directory? And then Spec and workgroups, for example, could be other top-level directories alongside that?

I think it should be possible, but may require some fiddling on our end. I'll sync up with @BUYMERCIER and see if we can find some time to play with that.

**Comment by Mengerian** [comment]
> Good points – we could begin labeling issues / PR's with website vs specifications to keep things a bit more color coded and easier to digest and filter.

Cool, the new label markups look good!

**Comment by ledailong** [comment]
Vào 03-12-2018 22:21, "Andrea Suisani" <notifications@github.com> đã viết:
