### ISSUE TITLE
Cash Accounts

### ISSUE THREAD

**Issue by monsterbitar** [bitcoincashorg/bitcoincash.org#186]
Requesting the 0x 01010101 identifier for the Cash Accounts protocol.

A display name for the protocol: Cash Accounts
An author (or list of authors): Jonathan Silverblood
A URL pointing to the specification of the protocol: https://gitlab.com/cash-accounts/specification (not yet published)

**Comment by monsterbitar** [comment]
System is now live - please add the protocol identifier.

**Comment by BUYMERCIER** [comment]
> Add CashAccount to projects
> https://cashaccount.info

**Comment by Mengerian** [comment]
Resolved: https://github.com/bitcoincashorg/bitcoincash.org/pull/327
