### ISSUE TITLE
Add LocalBitcoinCash.org

### ISSUE THREAD

**Issue by MobTwo** [bitcoincashorg/bitcoincash.org#223]
https://www.bitcoincash.org/buy-bitcoin-cash.html - Please include https://LocalBitcoinCash.org/Shopping/ and https://LocalBitcoinCash.org/Work/ in this page. We connect users into the global Bitcoin Cash economy to trade with each other, products and services, privately and securely.

https://www.bitcoincash.org/buy-bitcoin-cash.html (under "Buy in Person" section), will you add https://localbitcoincash.org/ to this please?

https://www.bitcoincash.org/spend-bitcoin-cash.html - Please include https://LocalBitcoinCash.org/Work/ and https://LocalBitcoinCash.org/Shopping/ in this page. People can actually spend Bitcoin Cash to buy stuff, hire people to do work, pay their utility bills, tip their favorite Youtubers, etc on LocalBitcoinCash.

https://www.bitcoincash.org/accept-bitcoin-cash.html - Please include https://LocalBitcoinCash.org/Pay/ to this page or possibly a mention that they can setup this payment widget on their website? The steps to integrate this Bitcoin Cash payment widget is available on our platform.

If you want more info about the full potential of LocalBitcoinCash, please take a look at this https://localbitcoincash.org/img/LocalBitcoinCash_Infographics.png

Our team spent a lot of time and effort into building up the platform and onboarding new users into the Bitcoin Cash economy and would appreciate all the help.

**Comment by BUYMERCIER** [comment]
#237 

Thank you @MobTwo will review this ASAP!
