### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [bitcoincashorg/bitcoincash.org#227]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support BCH on our service for a long time and we have been exchanging BCH for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by BUYMERCIER** [comment]
Hi Nicolas, thank you for your interest in Bitcoin Cash and BitcoinCash.org!
You can reach out to me using handle `@merc1er` on Telegram or other social media, I will guide you through the process of adding a listing to the website.

**Comment by BUYMERCIER** [comment]
Hi Nicolas, thank you for your interest in Bitcoin Cash and BitcoinCash.org!
You can reach out to me using my handle @merc1er on Telegram or other social media, I will guide you through the process of adding a listing to the website :)
