### ISSUE TITLE
Host Intro Video differently for Chinese website

### ISSUE THREAD

**Issue by merc1er** [bitcoincashorg/bitcoincash.org#236]
As YouTube is not available by default within China

**Comment by maplesyrupsucker** [comment]
@BUYMERCIER any recommendations on chinese friendly video hosts?

**Comment by BUYMERCIER** [comment]
Thank you for the recommendation, I will definitely check this out.
I was thinking about self-hosting the video and use the HTML5 player

**Comment by merc1er** [comment]
#294
