### ISSUE TITLE
Add Piixpay to services - revise logo

### ISSUE THREAD

**Issue by maplesyrupsucker** [bitcoincashorg/bitcoincash.org#245]
https://www.piixpay.com/

![image](https://user-images.githubusercontent.com/3764321/50732546-7b356280-11c0-11e9-9a5e-2e767c0e4b4d.png)

**Comment by maplesyrupsucker** [comment]
@BUYMERCIER looks like we already have them - they just have a new logo. We should update that

**Comment by BUYMERCIER** [comment]
#249 Here you go @maplesyrupsucker
