### ISSUE TITLE
Add Badger Wallet & Badger Button

### ISSUE THREAD

**Issue by maplesyrupsucker** [bitcoincashorg/bitcoincash.org#256]
Badger Button > Services (https://developer.bitcoin.com/badger/docs/badger-button)

Badger wallet > Desktop: Windows / Mac / Linux (http://badger.bitcoin.com)

![badger](https://user-images.githubusercontent.com/3764321/51100710-a18b7b80-181a-11e9-99ab-8fccf0b24e1a.png)

**Comment by BUYMERCIER** [comment]
#297 for Badger Button
