### ISSUE TITLE
Blockchain wallet not given 1:1 BCH

### ISSUE THREAD

**Issue by arvind9** [bitcoincashorg/bitcoincash.org#271]
After BCH hordfork in all exchanges i have received 1:1 BCHabc and BCHsv but i have did not received any update on blockchain wallet and on 5 february there was a update but not received any forked coins 

so can you please tell me how i can get this forked coin in my wallet

**Comment by imaginaryusername** [comment]
This is not a support forum for web wallets, please go ask the provider.

**Comment by arvind9** [comment]
i am not asking about wallet support i am asking about bitcoincash 

why its not split in to bchabc  and bchsv you have to give clarification for this

**Comment by imaginaryusername** [comment]
No, this is 100% a wallet issue. Nobody at bitcoincashorg asked for the bsv split, nor is anyone here responsible for how wallet implementations handle your coins. In fact, people here *cannot* do anything about the behaviour of your "blockchain wallet", which I assume is a wallet provided by blockchain.com. 

Also note that "bchabc" does not exist, there's only BCH. 

@BUYMERCIER please close the thread.

**Comment by arvind9** [comment]
i have bch in blockchain i am asking how i will get BCH and BSV both what is the solution...

**Comment by imaginaryusername** [comment]
Ask your wallet provider. Seriously. They have the "solution", or not, nobody else can possibly answer that question.

**Comment by maplesyrupsucker** [comment]
Closing this issue. @arvind9 please enquire about support from your wallet provider regarding getting fork or airdrop coins. We can't give advice here on how to split your coins.
