### ISSUE TITLE
Add Neutrino Wallet

### ISSUE THREAD

**Issue by JettScythe** [bitcoincashorg/bitcoincash.org#333]
The gcash/BCHD guys have been hard at work! Might be good to have a privacy focused wallet listed.

**Comment by merc1er** [comment]
Could you please provide with a website/GitHub repo? :) 

I have seen this wallet in action a few times and found it very buggy, sometimes unusable.

**Comment by JettScythe** [comment]
https://github.com/gcash/android-neutrino
website is coming soon!

**Comment by merc1er** [comment]
Closing for now as the wallet is unstable and still under development. 
Will list it once it has a stable release :)
