### ISSUE TITLE
关于Segwit恢复的问题

### ISSUE THREAD

**Issue by BlackEyesForThree** [bitcoincashorg/bitcoincash.org#357]
您好，今天我使用了huobi ，我误将我的bitcoincash提现到了比特币以三开头的隔离验证地址，请问我现在如何恢复呢？我有我的比特币地址的私钥，但是我尝试过了所有的bch手机端和网页端的钱包，都无法恢复我误转的bitcoincash。

**Comment by BlackEyesForThree** [comment]
这是我的提现的bitcoin地址：3BfSGVEMH6kynu1FkzZVSq8A5YKAMXbZnt

**Comment by imaginaryusername** [comment]
隔离验证地址在BCH上是无法由用户自己提取的; 如果金额很小，建议放弃，由大矿池為你恢复的手续很麻烦，而且不保证成功。

如果金额很大：
1. 先不要从同地址发BTC! 只要你的script还没被看到，就没有不良矿工横刀抢币的风险。如你已经从同一地址发了BTC，没人能保证这些币的去向 - 不良矿工可能据為己有，善意的矿工可能返还给火币。

2. 发信给已知有代客恢复服务的几家大矿池 - pool.bitcoin.com, btc.com, viabtc.com, btc.top 都有类似服务，然后与他们沟通寻找解决方法。bitcoincash.org维护团队没有能帮忙的成员。

**Comment by BlackEyesForThree** [comment]
谢谢，数额很大，我已经联系了一些矿池服务。然后接下来应该可以继续做了
