### ISSUE TITLE
how to get the  tags

### ISSUE THREAD

**Issue by zhangliang7190** [bitcoincashorg/bitcoincash.org#380]

**Comment by zhangliang7190** [comment]
I want to use the APIs to monitor if your rep has big change by tags.
but I  don't have success to use   "https://api.github.com/repos/bitcoincashorg/bitcoincash.org/tags" .
so ,how can I do it ?
thanks all .

**Comment by merc1er** [comment]
We do not use releases for the website. Every new commit gets deployed continuously.
