### ISSUE TITLE
An error occured: 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

### ISSUE THREAD

**Issue by gitchand** [bitcoincashorg/bitcoincash.org#386]
While pushing a bch tx, I am getting the error:
16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

Please help me to sort out this

**Comment by merc1er** [comment]
This is the repository for BitcoinCash.org website. Please contact the wallet service you are using for support.
