### ISSUE TITLE
Wallets - Update Badger

### ISSUE THREAD

**Issue by SpicyPete** [bitcoincashorg/bitcoincash.org#421]
Consider adding the `Badger` wallet to iOS and Android.  And update the logo

- iOS 
  - https://apps.apple.com/fr/app/badger-wallet-by-bitcoin-com/id1464796422?l=en
- Android
  - https://play.google.com/store/apps/details?id=com.badgermobile&hl=en_CA
- Chrome / Brave
  - https://chrome.google.com/webstore/detail/badger-wallet/jadobjbcgibiopkifknkfnohlelpocll?hl=en
- Firefox
   - https://addons.mozilla.org/en-CA/firefox/addon/badger-wallet/

**Comment by merc1er** [comment]
Would you be able to create a pull request with those changes?
