### ISSUE TITLE
Remove the incomplete IFP proposal from May 2020 upgrade, it is past feature freeze

### ISSUE THREAD

**Issue by ftrader** [bitcoincashorg/bitcoincash.org#454]
I've raised PR https://github.com/bitcoincashorg/bitcoincash.org/pull/453  to revert the IFP from the 15 May 2020 spec.

The IFP change is not only highly controversial, it is still incompletely specified and its proposed BIP9-like activation mechanism brings strong risks for a chain split due to minority hashrate of Bitcoin Cash network in total of SHA256.

It would be irresponsible in my opinion not to revert and at least postpone the IFP specifiication to subsequent upgrades.

Also, I want to say that PR#444 merge procedure was highly irregular for such a controversial change - being merged by the PR's own proposer. Is there no process that prevents this? If so, the process seems lacking the necessary safeguards against introducing controversial, potentially chain-splitting consensus changes.

**Comment by imaginaryusername** [comment]
Bitcoin Cash and bitcoincash dot org is considered Amaury's private property at this repo and hence none of these concerns apply, the owner can do whatever he pleases to his toy. Recommend closing followed by formal registration at the authorities as such.

**Comment by BigBlockIfTrue** [comment]
Dear repository owners,

I think you have two options here:

1. If you agree with ftrader, please merge #453 immediately
2. If you agree with imaginary_username, please respond with "We do whatever the fuck we want. Fuck you."

I think you are decent people so I fully expect you to pick the first option. But please make your choice known either way. Thanks.

**Comment by ftrader** [comment]
Five days without response from any maintainer of this important repository.

I think that they do not agree with reverting the incomplete IFP specification despite the protest from the community.

**Comment by ftrader** [comment]
The utter lack of response from the maintainers of this repository on this Issue and to [my enquiry about my removal without noticed from the Bitcoin Cash organization on Github](https://github.com/bitcoincashorg/bitcoincash.org/issues/460) can not be excused in any way.

The specifications in this repository no longer represent the Bitcoin Cash community consensus.

Bitcoin Cash Node will not follow the IFP specification, which is even incomplete, with the document stating "*A more detailed specification of the IFP is in progress*" since more than 3 weeks, and nowhere is there any indication of a time schedule for its completion.

The Bitcoin Cash user community deserves better.
