### ISSUE TITLE
Who removed me from Bitcoin Cash org and why?

### ISSUE THREAD

**Issue by ftrader** [bitcoincashorg/bitcoincash.org#460]
In https://github.com/bitcoincashorg/bitcoincash.org/pull/453 I asked about 3 times, and then the PR was locked (closed) without any answer about the process, or indeed addressing the substance of the pull request to revert the IFP commit.

So I will ask again:

> I noticed I was removed from bitcoincashorg organization on github on March 3 by some administrator of the org.

> It was not correlated to any action of mine (my last GH action prior to raising this PR was on Feb 22).
>The time of receipt of the automated notification email from Github is 3 Mar 2020 18:12:50 UTC.

> Can someone explain to me why I was removed from this repository which is nominally the location of the common Bitcoin Cash specification?

> @Mengerian @deadalnix @jasonbcox who removed me from the Bitcoin Cash org, and why?

**Comment by ftrader** [comment]
Maybe I can get an answer here.

I don't know a reason why the administrators of this repository (I don't know who controls it now) should not want to be transparent about the process that led to removing me.

**Comment by merc1er** [comment]
@deadalnix owns it as well as the domain name bitcoincash.org, and very likely removed you from the org.
The people with admin rights here are @Mengerian @deadalnix @jasonbcox.
