### ISSUE TITLE
Bitcoin Cash colours

### ISSUE THREAD

**Issue by maesitos** [bitcoincashorg/bitcoincash.org#55]
Here https://www.bitcoincash.org/graphics/ there branding guidelines suggest to use orange. Any possibility to change it to green? More and more people are using the green colour. 

BCH for life.

**Comment by schancel** [comment]
And did you ask those people to use Orange?

**Comment by maesitos** [comment]
no

**Comment by maesitos** [comment]
No, and I use green too.

**Comment by jasonbcox** [comment]
I think we're going to have to agree to disagree here.  This topic has been beaten to death.

**Comment by maplesyrupsucker** [comment]
Marking as closed - let's avoid Bikeshedding (https://en.wiktionary.org/wiki/bikeshedding) and just continue making Bitcoin Cash the best money for the world.
