### ISSUE TITLE
The snake seems to be eating its tail: [#1121/files#diff](https://github.com/github/opensource.guide/pull/1121/files#diff-31669052b00291ed5f9e4cd6db9fdd6bR31-R33) ;-)

### ISSUE THREAD

**Issue by nhutran1201** [bitcoincashorg/bitcoincash.org#556]
The snake seems to be eating its tail: [#1121/files#diff](https://github.com/github/opensource.guide/pull/1121/files#diff-31669052b00291ed5f9e4cd6db9fdd6bR31-R33) ;-)

I'll revisit this in a few days once there is a difference between my `translation_branch`& `upstream/master` to check whether the above initial idea is viable.

__Originally posted by @katrinleinweber in https://github.com/github/opensource.guide/issues/1119#issuecomment-536685634__

**Comment by jasonbcox** [comment]
Please stop linking unrelated projects.
