### ISSUE TITLE
Will you guys remove Coinbase from the site due to not using Bitcoin ABC?

### ISSUE THREAD

**Issue by RowanSkie** [bitcoincashorg/bitcoincash.org#656]
So, I've noticed there's a PR which removed Bitcoin Unlimited from the BitcoinCash.org site. If you guys were gonna do that, why not remove Coinbase for choosing other not implementing Bitcoin ABC for their Bitcoin Cash transactions, especially on Coinbase Pro?

**Comment by melroy89** [comment]
I think Coinbase is now using BCH (previously known as Bitcoin ABC) for their Bitcoin Cash transactions: https://www.coinbase.com/price/bitcoin-cash

Also Bitcoin Unlimited is still listed. 

Note, the current git repo: https://github.com/zquestz/bitcoincash

**Comment by RowanSkie** [comment]
This issue was made during pre-ABC split, and it was focused on them. Thanks for reminding me to close it.
