### ISSUE TITLE
Suggest URI registration with IANA

### ISSUE THREAD

**Issue by markblundeberg** [bitcoincashorg/bitcoincash.org#82]
The cashaddr addresses look like URIs. From my brief googling on this topic, it looks like it's not too much trouble to get a 'provisional' registration on the official IANA list of URI prefixes:
https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

So, I'd suggest registering "bitcoincash:".

The appropriate guidelines for provisional registration are here: https://tools.ietf.org/html/rfc7595#page-9
I think you'd just write a brief rationale and then email one of the people there (Graham Klyne?) and that's it.

**Comment by BUYMERCIER** [comment]
Registration request submitted. 
Thank you 😃
